version: 2
jobs:
    build:
        working_directory: ~/rockaway-beach
        docker:
            - image: python:3.6.0
        steps:
            - checkout
            - run: echo "hello world"
            - scp -r * marineboudeau@marineboudeau.com:/home/rockaway-beach/
